sonar.projectKey=andysenclave_lunar-divide-folio
sonar.organization=andysenclave
sonar.sources=app,components,config,context,hooks,theme
sonar.tests=__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.tsx,**/*.spec.tsx,**/types.ts,**/data/**
sonar.qualitygate.wait=true
