import type { WorkExperience } from './types';

export const EXPERIENCE_DATA: WorkExperience[] = [
  {
    id: 'nous',
    period: 'Dec 2021 — Present',
    role: 'Technical Lead → Senior Technical Lead',
    company: 'Nous Infosystems',
    location: 'Kolkata, India',
    type: 'engineering',
    current: true,
    description:
      'Leading frontend engineering for enterprise clients in financial services — Fitch Ratings (2021-2023) as Technical Lead and Royal Bank of Canada (2023-Present) as Senior Technical Lead. Managing 8 UI developers across 6 squads.',
    highlights: [
      'RBC: 8 direct reports, 21 UI team total, ~50 member program across 6 squads',
      'Fitch: Led 5 UI devs across Committee (2) + Workflow (3) squads',
      'CI/CD ownership: Jenkins, Helios, Docker with 85% test coverage gate',
      'GitHub Copilot Certification (GH-300) — 92% score',
      'COE contributor: Recruited and trained new associate developers',
    ],
    technologies: [
      'React',
      'React Native',
      'TypeScript',
      'GraphQL',
      'Node.js',
      'Spring Boot',
      'Jenkins',
      'Docker',
    ],
  },
  {
    id: 'localoi',
    period: 'Aug — Dec 2021',
    role: 'CTO & Co-founder',
    company: 'Localoi.in',
    location: 'Kolkata, India',
    type: 'engineering',
    description:
      'Co-founded hyperlocal e-commerce platform. Built 3-app ecosystem from scratch — consumer, merchant, and delivery partner apps.',
    highlights: [
      'Built 3-app ecosystem: Localite (consumer), Business Partner, Delivery Partner',
      'Designed full-stack architecture: React Native, Next.js, NestJS, GraphQL',
      'Led team of 3 developers + video editing team for content marketing',
      'Integrated Razorpay, Google Maps, WhatsApp Business API, FCM',
      'Campaign results: ~10K views, ~500+ engagements on launch content',
    ],
    technologies: [
      'React Native',
      'Next.js',
      'NestJS',
      'GraphQL',
      'MongoDB',
      'MySQL',
      'Docker',
    ],
  },
  {
    id: 'fincompare',
    period: '2019 — 2021',
    role: 'Frontend Engineer → Senior Fullstack Engineer',
    company: 'FinCompare GmbH',
    location: 'Berlin, Germany',
    type: 'engineering',
    description:
      'Started as Frontend Engineer, grew to Senior Fullstack Engineer at FinTech startup. Built shared component library and SME onboarding flows.',
    highlights: [
      'Led team of 3 UI developers as Senior Fullstack Engineer',
      'Built reusable component library from scratch',
      'Implemented SME financing onboarding flows',
      'Met Dan Abramov at a Berlin hackathon 🎉',
    ],
    technologies: ['React', 'Redux', 'Styled Components', 'Node.js', 'Jest'],
  },
  {
    id: 'cognizant-oslo',
    period: '2018 — 2019',
    role: 'Onsite Coordinator & Team Lead',
    company: 'Cognizant (at Storebrand)',
    location: 'Oslo, Norway',
    type: 'engineering',
    description:
      'Led knowledge transition for React applications. Full ownership of TrackMyCase application with Express.js backend.',
    highlights: [
      'Full-stack ownership: TrackMyCase customer portal',
      'Express.js backend with REST APIs',
      'Real-time updates with MQTT + CouchDB document storage',
      'Knowledge transition lead for React applications',
    ],
    technologies: ['React', 'Redux Saga', 'Express.js', 'MQTT', 'CouchDB'],
  },
  {
    id: 'cognizant-kolkata-norway',
    period: '2016 — 2018',
    role: 'Full Stack JavaScript Developer',
    company: 'Cognizant (Norway Insurance)',
    location: 'Kolkata, India',
    type: 'engineering',
    description:
      'Worked on Norway Insurance client (Storebrand) from Kolkata before transitioning to onsite role in Oslo. Full stack development with React and Node.js.',
    highlights: [
      'Norway Insurance client (Storebrand)',
      'React and Node.js full stack development',
      'Prepared for onsite transition to Oslo',
    ],
    technologies: ['React', 'Node.js', 'JavaScript', 'Redux'],
  },
  {
    id: 'cognizant-kolkata',
    period: '2015 — 2016',
    role: 'Associate Software Developer',
    company: 'Cognizant (Belgium Insurance)',
    location: 'Kolkata, India',
    type: 'engineering',
    description:
      'European Insurance vertical with major clients like AXA, Allianz, and Zurich. Built mobile apps for innovation demos. Hackathon champion.',
    highlights: [
      'Belgium Insurance clients: AXA, Allianz, Zurich',
      'Built native and hybrid mobile apps for innovation demos',
      'Multiple hackathon wins',
    ],
    technologies: ['JavaScript', 'AngularJS', 'Cordova', 'Mobile Development'],
  },
  {
    id: 'cognizant-chennai',
    period: '2013 — 2015',
    role: 'Programmer Analyst',
    company: 'Cognizant Technology Solutions',
    location: 'Chennai, India',
    type: 'engineering',
    description:
      'Started career in US Healthcare domain. Progressed from trainee to Programmer Analyst. Center of Excellence member.',
    highlights: [
      'US Healthcare client',
      'Progressed from trainee to Programmer Analyst',
      'Center of Excellence member',
    ],
    technologies: ['JavaScript', 'AngularJS', 'Java', 'jQuery'],
  },
];
